In [17]:
import numpy as np

with open('sample_input') as file:
    octopus = np.array([[int(i) for i in line] for line in file.read().splitlines()])

print(octopus)

[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]


In [121]:
import numpy as np

class Octopus:

    def __init__(self):
        with open('input') as file:
            self.grid = np.array([[int(i) for i in line] for line in file.read().splitlines()])
            self.already_flashed = []
            self.total_flash = 0

    def add_step(self) -> None:

        def increment_all(self) -> None:
            for line_index, line in enumerate(self.grid):
                for col_index, elem in enumerate(line):
                    self.grid[line_index, col_index] += 1

        def flash_this_octopus(self, line_index: int, col_index: int) -> None:
            if line_index > 0:
                self.grid[line_index - 1, col_index] += 1       # top
            if line_index > 0 and col_index < 9:
                self.grid[line_index - 1, col_index + 1] += 1   # top right
            if col_index > 0:
                self.grid[line_index, col_index - 1] += 1       # left
            if line_index < 9 and col_index > 0:
                self.grid[line_index + 1, col_index - 1] += 1   # bot left
            if line_index > 0 and col_index > 0:
                self.grid[line_index - 1, col_index - 1] += 1   # top left
            if col_index < 9:
                self.grid[line_index, col_index + 1] += 1       # right
            if line_index < 9:
                self.grid[line_index + 1, col_index] += 1       # bot
            if line_index < 9 and col_index < 9:
                self.grid[line_index + 1, col_index + 1] += 1   # bot right

            self.already_flashed.append((line_index, col_index))

        def flash_all(self) -> None:
            self.already_flashed = []
            high_stop = False

            while high_stop == False:
                
                octopus_seen = 0
                low_stop = False
                
                for line_index, line in enumerate(self.grid):
                    for col_index, elem in enumerate(line):
                        octopus_seen += 1
                        if (elem > 9) and ((line_index, col_index) not in self.already_flashed):
                            flash_this_octopus(self, line_index, col_index)
                            low_stop = True
                            break
                    
                    if low_stop == True: break
                
                if octopus_seen == 100: high_stop = True


        def replace_flashed_zero(self) -> None:
            for line_index, line in enumerate(self.grid):
                for col_index, elem in enumerate(line):
                    if self.grid[line_index, col_index] > 9:
                        self.grid[line_index, col_index] = 0
                        self.total_flash += 1

        increment_all(self)
        flash_all(self)
        replace_flashed_zero(self)


In [122]:
octopus = Octopus()

for i in range(100):
    #print(f'step {i + 1}')
    octopus.add_step()
    #print(octopus.grid)

print(octopus.grid)

print(octopus.total_flash)

[[6 7 9 2 2 2 7 5 4 4]
 [7 9 2 2 2 2 2 7 5 4]
 [9 3 2 2 2 2 2 2 7 5]
 [1 5 3 9 2 2 2 2 3 7]
 [1 1 4 8 8 2 2 3 5 1]
 [1 1 8 5 5 7 2 4 1 1]
 [1 1 6 4 4 5 6 8 1 1]
 [1 7 5 4 4 4 4 5 8 1]
 [8 5 4 4 4 4 4 5 8 4]
 [6 8 4 4 4 4 4 5 3 3]]
1702


In [120]:
octopus.grid[1,0]

2